### ISSUE TITLE
AttributeError: 'list' object has no attribute 'intersection'

### ISSUE THREAD

**Issue by lezsakdomi** [CanonicalLtd/probert#77]
Ubuntu installer log:
```log
2019-12-22 17:18:03,207 block-discover:74 starting probe
2019-12-22 17:18:03,317 probert.multipath:37 Failed to run cmd: ['multipathd', 'show', 'maps', 'raw', 'format', '%w %d %N']
2019-12-22 17:18:03,328 probert.multipath:37 Failed to run cmd: ['multipathd', 'show', 'paths', 'raw', 'format', '%d %z %m %N %n %R %r %a']
2019-12-22 17:18:08,223 block-discover:99 probing failed restricted=True
Traceback (most recent call last):
  File "/snap/subiquity/1093/lib/python3.6/site-packages/subiquity/controllers/filesystem.py", line 89, in _probed
    storage = fut.result()
  File "/snap/subiquity/1093/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/snap/subiquity/1093/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/snap/subiquity/1093/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/snap/subiquity/1093/lib/python3.6/site-packages/subiquity/controllers/filesystem.py", line 126, in <lambda>
    lambda: self._bg_probe(["blockdev"]),
  File "/snap/subiquity/1093/lib/python3.6/site-packages/subiquity/controllers/filesystem.py", line 81, in _bg_probe
    return self.prober.get_storage(probe_types=probe_types)
  File "/snap/subiquity/1093/lib/python3.6/site-packages/subiquitycore/prober.py", line 69, in get_storage
    results = storage.probe(probe_types=probe_types)
  File "/snap/subiquity/1093/lib/python3.6/site-packages/probert/storage.py", line 169, in probe
    to_probe = probe_types.intersection(default_probes)
AttributeError: 'list' object has no attribute 'intersection'
2019-12-22 17:18:43,432 block-discover:86 ignoring result <Future at 0x7f646e9b3f60 state=finished returned dict> for timed out probe
```

... and it hangs :(

Maybe you could use a more massive solution on
https://github.com/CanonicalLtd/probert/blob/129c4c3a47f6fac56f7db672e783a1cb2694e37b/probert/storage.py#L169

The ubuntu installer ISO "startup screen" failed, but installing subiquity using apt (i.e. avoiding the snap package) and killing the snap process (meh it just restarted so I left that as-is) and then manually running `subiquity` worked somehow.

**Comment by OddBloke** [comment]
Hi @lezsakdomi, thanks for using Ubuntu, and thanks for this bug report! I believe this is actually a subiquity issue (as it is calling probert with incorrectly typed arguments), so I've opened https://bugs.launchpad.net/subiquity/+bug/1858447.

As I don't believe that there are any probert changes needed, I'm going to close this out. Please feel free to reopen or comment here if you think that that is incorrect!
